#+TITLE: Doom Emacs Configuration
#+AUTHOR: Jean-Michel Gorius
#+STARTUP: showeverything

* PRELUDE
Make this file run (slightly) faster with lexical bindings. See
[[[[https://nullprogram.com/blog/2016/12/22/]]][this blog post by Chris Wellons]]
for all the details.
#+begin_src emacs-lisp :tangle yes
;;; config.el -*- lexical-binding: t; -*-
#+end_src

* PERSONAL INFORMATION
Emacs uses a few bits of personal information that are transmitted to GPG, email
clients and used for file templates.
#+begin_src emacs-lisp :tangle yes
(setq user-full-name "Jean-Michel Gorius"
      user-mail-address "jean-michel.gorius@ens-rennes.fr")
#+end_src

* THEME
There are two different ways to load a theme in Doom Emacs. Both assume that the
theme is installed and available. We can either set ~doom-theme~ or manually
load a theme using ~load-theme~.
#+begin_src emacs-lisp :tangle yes
(setq doom-theme 'doom-one)
#+end_src

* ORG MODE
Set the default location for =org-mode= files. Note that this must be set before
=org= actually loads.
#+begin_src emacs-lisp :tangle yes
(setq org-directory "~/org/")
#+end_src

Set additional =org-mode= parameters.
#+begin_src emacs-lisp :tangle yes
(after! org
  (setq org-agenda-files '("~/org/agenda.org" "~/org/todo.org"))
  (setq org-log-done 'time))
#+end_src

Define =org-capture= templates.
#+begin_src emacs-lisp :tangle yes
(after! org
  (setq org-capture-templates
        '(("t" "Todo" entry (file+headline "~/org/todo.org" "Tasks")
           "* TODO %?\n  %i")
          ("n" "Personal note" entry (file+headline "~/org/notes.org" "Inbox")
           "* %?\nCaptured on %U\n  %i\n"))))
#+end_src

Disable the fill column indicator line for =org= files.
#+begin_src emacs-lisp :tangle yes
(setq-hook! 'org-mode-hook fill-column nil)
#+end_src

* GENERAL APPEARANCE SETTINGS
Who doesn't display line numbers? Seriously?
#+begin_src emacs-lisp :tangle yes
(setq display-line-numbers-type t)
#+end_src

When creating a new window, take window space from all windows, not just the
current one.
#+begin_src emacs-lisp :tangle yes
(setq-default window-combination-resize t)
#+end_src

Stretch the cursor to the glyph width in case we are working with
non-standard-sized glyphs.
#+begin_src emacs-lisp :tangle yes
(setq-default x-stretch-cursor t)
#+end_src

Use Unicode ellipsis characters instead of '...' when truncating lines. This
saves up some space.
#+begin_src emacs-lisp :tangle yes
(setq truncate-string-ellipsis "…")
#+end_src

* UNDO AND SAVE SETTINGS
Raise the undo limit to 100MB and enable fine undo mode. Outside of fine edit
mode, all editing operations performed while in insert mode are treated as a
single blob. We prefer to have finer grain control over what has to be undone
when exiting insert mode. Also enable auto-saving because, well, you never know.
#+begin_src emacs-lisp :tangle yes
(setq undo-limit 100000000
      evil-want-fine-undo t
      auto-save-default t)
#+end_src

* EDITING EXPERIENCE
Iterate through CamelCase words instead of treating them as a single unit.
#+begin_src emacs-lisp :tangle yes
(global-subword-mode 1)
#+end_src

Turn off ~visual-line-mode~ and enable ~auto-fill-mode~ for all text modes. This
helps us stay inside of the character width limit defined by the fill column.
#+begin_src emacs-lisp :tangle yes
(remove-hook 'text-mode-hook #'visual-line-mode)
(add-hook 'text-mode-hook #'auto-fill-mode)
#+end_src

Disable =mixed-pitch= when entering Zen mode. The mixed typefaces don't look
very nice and I prefer to stick with the monospaced font used in normal editing
mode.
#+begin_src emacs-lisp :tangle yes
(remove-hook 'writeroom-mode-hook #'+zen-enable-mixed-pitch-mode-h)
#+end_src
